### ISSUE TITLE
Workflow can skip deploys, which are required for merge

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-forest-client-api#113]
Action updates are not triggering builds and deployments, which prevents merge.

` if: always() && (needs.build-backend.result == 'success') && github.actor != 'dependabot[bot]'`
https://github.com/bcgov/nr-forest-client-api/actions/runs/4206345685/workflow#L156

Example.
https://github.com/bcgov/nr-forest-client-api/pull/112

**Comment by paulushcgcj** [comment]
Solved during PR #112
