### ISSUE TITLE
Get proxy account for FOREST_CLIENT table

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forest-client-api#14]
Need to talk to the data custodian. Chantelle knows who they are.

https://apps.nrs.gov.bc.ca/int/confluence/display/AR/Data+Integration

There are a fair number of pre-requisites and process around data integration. This confluence doc is a good checklist, but I'll copy the checklist over here as well so we can track progress.

- [x] Has the Team identified the data\information required for the business needs?
- [x] Has the Team documented the business needs as related to the data sought. https://github.com/bcgov/forest-client-api/wiki/Business-Requirements#fom
- [x] Has the Team identified the source of the data\information - this includes the object\table\schema sources and database instances?
- [ ] Has the Team identified the security classifications of the data\information identified**. Has the Data Custodian been identified, is it clear how the data can be shared, and to whom? (ie. is it open, public, government only, named user?)
- [ ] Has the Team documented the source location, name and security classification of the data sought? (If so provide source/link/documents)
- [ ] Has the Team discussed with the Data Custodian(s) the reason and approach for accessing their data and have approval to proceed?
- [ ] Has the Team documented the Data Custodian approval (If so provide source/link/documents)
- [ ] Has the Team discussed with the Privacy and Security Teams to assess the level of documentation, re-assessment of PIA/STRA/SOARs required and have  approval to proceed?
- [ ] Has the Team documented the Privacy and Security approvals (If so provide source/link/documents)
- [ ] Has the Team discussed the architectural approach with IIT Architects to ensure strategic direction and alignment. This includes such details as proposed approach, such as proxy account creation in Oracle, role grants required, (CRUD) level of access, technology stack to be used, extract-transform-load requirements, sources and destination routes. 
- [ ] Has the Team documented the approach for accessing the data (If so provide source/link/documents). (This service could be provided by IIT Architects)
- [ ] Has the Team prepared scripts for the Database proxy account creation (requested by the DBA team via AEA/MAS/BPM? team via a Jira Ticket in the Team's Jira Project team space as an RFC/RFD?)
- [ ] Has the Team requested the implementation via the appropriate/communicated channels? (see above item that needs more clarity)
- [ ] Has the requested IIT Team actioned and completed the request?
- [ ] Has the Team documented the actions?
- [ ] Other items may be necessary if access is via alternate routes such as a WebADE/WSO2 service client access??
- [ ] Implement the data integration
- [ ] Documentation: IRS updated
- [ ] Documentation: Architecture's Confluence Space
- [ ] Documentation: Confluence Project Space with links to Jira
- [ ] Documentation: Database/Schema documentation spaces?

**Comment by amee99073** [comment]
request for access to the view sent via email Feb 7, 2022

**Comment by webgismd** [comment]
https://apps.nrs.gov.bc.ca/int/jira/browse/INFRA-16102 next step initiated with the Security team and request a data classification

**Comment by ConradBoydElliottGustafson** [comment]
[2:48 PM] Douville, Michelle R IIT:EX
HERE is the RFD for creating the proxy account https://apps.nrs.gov.bc.ca/int/jira/browse/FSAMP-30

**Comment by ConradBoydElliottGustafson** [comment]
Proxy account created in 4temp1 (dev?). Still waiting for proxy accounts for test and prod.

**Comment by ConradBoydElliottGustafson** [comment]
New task: Update the FSA-script repo and document the process with the audience being DBAs.

**Comment by gormless87** [comment]
Transfer to Team Alliiance(?)

**Comment by paulushcgcj** [comment]
Closing this issue as it seems lost in time and looks like it lost its relevance.
