### ISSUE TITLE
FSADT1-420: Update existing forest client api to use java

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forest-client-api#43]
[FSADT1-420](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-420) Update existing forest client api to use java

- Maria copy findbynumber and findallnonindividuals over to Maria’s branch
- Maria continue with apis:
    - [x] add findallnonindividuals request
    - [x] add find by name, filter by client type
    - [x] create a basic test
    - [x] add more core config
    - [x] redirect base url to swagger page
- Catherine:
    - [x] create oracle connection locally and basic api
    - [x] create docker file
    - [x] enable basic pipeline
    - [x] check how to make oracle connection in openshift
    - [x] enable swagger
    - [x] check Postgres connection
    - [x] update openshift API Gateway to the new api
- Maria & Catherine: think about login protection, through API Gateway, or self protect?

Tutorial:
[nr-arch-templates for remote oracle connection through openshift for java app](https://github.com/bcgov/nr-arch-templates/blob/main/apis/java/quarkus-legacy-oracle/.pipeline/openshift/Dockerfile)
[spring boot simple start](https://spring.io/guides/gs/rest-service/)
[spring boot oracle db example](https://spring.io/guides/tutorials/rest/)

Support oracle connection in openshift:
- InstallCert.java file is used to auto grab certificate (we can just use it, no need to modify anything)
- startup.sh run the command to setup certificate automatically and then start the app

**Comment by mamartinezmejia** [comment]
For this task we will use Spring Boot V2 and Maven aiming to upgrade to V3 as soon as it is available.

Here is what other teams are using and their reasons:

- Quarkus because Spring Boot does not provide native image support
- Quarkus does not have GA for Gradle
- Native images are ideal for cloud native deployments
- Native images are strongly encouraged if no oracle DB connection is required.

**Comment by MCatherine1994** [comment]
examples to setup two dbs: 
https://medium.com/javarevisited/configure-multiple-data-sources-postgres-oracle-in-a-spring-boot-application-72b28a9e6ea9
https://www.infoq.com/articles/Multiple-Databases-with-Spring-Boot/
https://stackoverflow.com/questions/30337582/spring-boot-configure-and-use-two-data-sources
https://medium.com/@joeclever/using-multiple-datasources-with-spring-boot-and-spring-data-6430b00c02e7

**Comment by MCatherine1994** [comment]
ref: #46 
ref: #47 
ref: #48 
ref: #49
