### ISSUE TITLE
FSADT1-499: Use db proxy account in pipeline

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forest-client-api#58]
[FSADT1-499](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-499) Get database credentials from vault
- integrate the production db proxy account in pipeline
- publish the api to api gateway

**Comment by MCatherine1994** [comment]
Need to meet with One Team first to ask how to get access to the db credentials, maybe using a token so could read db credentials in pipeline

**Comment by paulushcgcj** [comment]
Closing this as it was merged
