### ISSUE TITLE
Document API architecture

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forest-client-api#6]
We had an informal team discussion at standup.

Assume for now:
Running on OpenShift
Use the FOM tech stack (Nest.JS on Node)
Read-only encrypted listener into FC public view
GitHub actions for CI/CD (based on Greenfield pipeline project)
Set it up through the API Gateway

AC: Document this

Documented here for now: https://github.com/bcgov/forest-client-api/wiki/Architecture

**Comment by webgismd** [comment]
same as issue # 12 -- reviewed this - https://github.com/bcgov/nr-forest-client-api/wiki I think this looks good for when we want to revisit it.. @mishraomp -- https://quarkus-orcl-245e18-dev.apps.silver.devops.gov.bc.ca/q/swagger-ui/

**Comment by mishraomp** [comment]
Adding the link to the git repo. https://github.com/bcgov/nr-arch-templates/tree/main/apis/java/quarkus-legacy-oracle
