### ISSUE TITLE
FSADT1-508: create one search endpoint (with text parameter either on clientName or clientNumber)

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forest-client-api#64]
[FSADT1-508](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-508) create one search endpoint (with text parameter either on clientName or clientNumber)

One search endpoint to allow search based on clientName or clientNumber

Requested by Ian Liu from fingerprint team

**Comment by paulushcgcj** [comment]
Implemented as part of #66
