### ISSUE TITLE
Request encrypted listener for forest client data

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forest-client-api#8]
Talk to Pete and Soman. 

Do we need a separate one for DEV, TEST, PROD?

Probably want an RFC ticket and 3 RFD tickets.

Michelle will set up the JIRA ticket.

**Comment by webgismd** [comment]
Is this issue blocked by picking an API Architecture? (I guess unless we decided to leverage something like FME Server to sync data- which is onprem)? I suspect it is blocked by DBA time, PIA/STRA, on prem change request processes .. -- an Oracle proxy account will be needed to access the current forest client data regardless.

**Comment by ConradBoydElliottGustafson** [comment]
I don’t think it’s actually blocked. We will need a proxy account no matter what we do (not sure if FME is an option or not?).

Although, PIA/STRA will be tricky if we don’t document our architecture. I think that was all I really meant.

**Comment by mishraomp** [comment]
not sure if GO lang has an oracle driver to connect to Oracle DB. if the FME server is pushing data to this API then it is OK.
@webgismd @ConradBoydElliottGustafson @franTarkenton

**Comment by ConradBoydElliottGustafson** [comment]
@mishraomp The idea for this API is to create the interface that will live long-term. Eventually the connection to Oracle will be deprecated. 

Quick google reveals a common package: https://pkg.go.dev/github.com/godror/godror

Having said that, I hear from @DerekRoberts that you have been looking at API dev templates, so I'm excited to see what you've been working on. Golang was just a "roll the dice" for a simple prototype (but I like it personally).

**Comment by DerekRoberts** [comment]
+1 for GoLang! :)

**Comment by mishraomp** [comment]
I am not sure if Go can support multiple data sources(Oracle and Postgres) at the same time, connection pooling, encrypted listeners all those items, I would love to see it in action, maybe something like Gin and GORM could be of help, as my knowledge on building APIs with GO is very limited.
https://github.com/gin-gonic/gin
https://github.com/go-gorm/gorm

I have tons of experience with node/express, Quarkus, Micronaut spring boot. I will be publishing sample APIs to the OS namespace that @DerekRoberts is providing access to, will keep you posted.

**Comment by DerekRoberts** [comment]
Good ol' Node can handle pretty much everything.  ;)

...Feels like time to book a meeting.

**Comment by ConradBoydElliottGustafson** [comment]
[2:52 PM] Douville, Michelle R IIT:EX
and here for encrypted listener RFD - https://apps.nrs.gov.bc.ca/int/jira/browse/FSAMP-31
