### ISSUE TITLE
Blank browser screen on initial app launch in new browser

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-forest-client-api#82]
**Describe the Bug**
When I launch the app by opening a new browser (e.g. after clearing history) and type in URL, I get a blank page. The web console shows the following error:
       Uncaught TypeError: Cannot read properties of null (reading 'fam_cognito_region')

**Expected Behaviour**
The application screen displays properly. This does happen when I refresh the page.

**Actual Behaviour**
Blank screen is displayed. In the code, it appears it is initializing main.ts and specifically awsExports _before_ env.js is called to initialize the environment. Perhaps move initializing of env.js into main.ts???

**Additional context**
Observed in Edge and Chrome.

**Comment by paulushcgcj** [comment]
This issue is not relevant anymore as only the API is present here. Closing

**Comment by basilv** [comment]
Sorry, raised issue for wrong repo. Not sure how that happened.
